### ISSUE TITLE
circular_storage thread checking mechanism problems

### ISSUE THREAD

**Issue by tap** [Cycling74/min-lib#10]
Currently, it seems the circular_storage (via allpass or similar) would need to be constructed in the audio thread, which is bad.

**Comment by nwolek** [comment]
@tap and I just had a quick Skype about this. The `m_thread` variable is currently set in the constructor, which will likely happen in a different thread than the audio calls. This is not necessarily a thread safety issue and should be permissible. The issue we really want to prevent is calling methods from the same circular_storage in different threads.

The solution we discussed is a new `check_thread` method. The features:

- `m_thread` would be set to NULL at construction
- first call to `check_thread` would set `m_thread`
- all subsequent calls to `check_thread` would test against the first call
- all calls to `check_thread` should be wrapped in preprocessor switches for debugging (i.e., `ifndef NDEBUG`)

**Comment by nwolek** [comment]
Hey @tap. Just found this note in the C++ header file for thread. Does this concern you?

// FIXME: pthread_t is a pointer on Darwin but a long on Linux. 
// NULL is the no-thread value on Darwin.  Someone needs to check 
// on other platforms.  We assume 0 works everywhere for now.

**Comment by nwolek** [comment]
Found this tip about testing against the default constructor:
https://stackoverflow.com/questions/35754337/is-there-a-null-value-for-stdthreadid/35754370

Also consulted this enter about the null state:
https://akrzemi1.wordpress.com/2011/12/06/null-state-part-i/

**Comment by nwolek** [comment]
Learned that if NDEBUG macro is defined, then assert() does nothing. Might make most sense to wrap our new `check_thread` in a call to `assert()`, rather than have a bunch of `#ifndef NDEBUG` blocks.

http://en.cppreference.com/w/c/error/assert

**Comment by tap** [comment]
That's an interesting approach. I hadn't thought of that. I think it is
worth experimenting with it!

best,
  Tim
