### ISSUE TITLE
check gain signs in allpass formula

### ISSUE THREAD

**Issue by nwolek** [Cycling74/min-lib#18]
Currently, our allpass is configured like this:

```y = alpha * x  +  x1  -  alpha * y1;```

This corresponds to the description in Moore 1990 *Elements of Computer Music* page 285. However, I was cross checking with the following sources today:

- Roads: *The Computer Music Tutorial* page 418
- Dodge-Jerse: *Computer Music* page 298
- Boulanger: *The Csound Book* page 483

They all describe the allpass filter configuration as the following (note the change in signs):

```y = -alpha * x  +  x1  +  alpha * y1;```

Should we change this? Moore 1990 does talk about the gain coefficient working between -1 and 0 and 1, and describes a difference in the frequency response between positive and negative values. I just worry our output will be backwards from the expectation of others.

**Comment by tap** [comment]
Thanks, @nwolek. You look to be correct. The algorithm I used was in error and I fixed it somewhere else but never propagated that fix back to Jamoma / Min-Lib.

**Comment by nwolek** [comment]
I'll take care of this fix.

**Comment by nwolek** [comment]
Hmm. I just checked this against my old reverb_bb code from 2002 here:

https://github.com/nwolek/LowkeyNW/blob/master/source/projects/nw.gverb_tilde/reverb_bb.cpp#L551

It appears to be using the `y = alpha * x + x1 - alpha * y1;` variation.

My code is based on Jon Dattorro's Effect Design series from Journal AES in 1997. He cites Moorer, so it makes sense that they would use the same algorithm.

I am now thinking we should leave it alone. The algorithm is well documented via comments in the code, but I would likely add a comment pointing back to Moorer as the source. 

We could also introduce a second operator that implements the Roads/Dodge-Jerse/Boulagner version, but that could get confusing.

**Comment by tap** [comment]
I'd like to change it, actually. While it produces an allpass magnitude response either way, the phase response ends up causing trouble.

It is also desirable to make this change for this allpass response to be consistent with the standard `allpass~` object in Max.
