### ISSUE TITLE
test impulse response from allpass after sudden drop in delay time

### ISSUE THREAD

**Issue by nwolek** [Cycling74/min-lib#19]
Some initial testing shows that we may get a few bad samples from the allpass object after a sudden drop in delay time. The operator function is here:

https://github.com/Cycling74/min-lib/blob/master/include/c74_lib_allpass.h#L75

The call to `write()` happens after two calls to `tail()`. Since the `write()` call is the function that actually increments the private variable `m_index`, that variable does not get updated until *after* the calls to `tail()` happen. I believe this means they are returning bad values.

Working on a test.

**Comment by tap** [comment]
I had a couple of questions in my code review for #21.

I'll leave this open for now as a reminder for those.

**Comment by tap** [comment]
Closing as per Skype conversation today.
