### ISSUE TITLE
circular_storage::clear() does more than zero contents

### ISSUE THREAD

**Issue by nwolek** [Cycling74/min-lib#20]
This comment is misleading or wrong:
https://github.com/Cycling74/min-lib/blob/master/include/c74_lib_circular_storage.h#L173

It says "Zero the contents" and then makes a call to `vector::clear()`

According to [C++ reference](http://www.cplusplus.com/reference/vector/vector/clear/) though, that function: 
"Removes all elements from the vector (which are destroyed), _leaving the container with a size of 0_." [emphasis added by me]

I think we want something to zero the contents and leave the size consistent. Am I right?

**Comment by nwolek** [comment]
Found one reference to options here: https://stackoverflow.com/questions/8848575/fastest-way-to-reset-every-value-of-stdvectorint-to-0

Since vector::fill() does not allocate new memory, that is likely the best option.

**Comment by tap** [comment]
Great catch! That's absolutely correct... for a filter. It's more ambiguous
in the general sense though. And circular_storage is supposed to be general.

So it sounds to me like circular_storage() needs a fill() method and the
allpass needs to call that. Do you agree?

best,
  Tim
