### ISSUE TITLE
Review all calls to circular_storage::clear()

### ISSUE THREAD

**Issue by nwolek** [Cycling74/min-lib#22]
I found this line in the code for delay - 

https://github.com/Cycling74/min-lib/blob/master/include/c74_lib_delay.h#L63

This is likely a place where we want to use the new circular_storage::zero() and there may be others.

We should sweep through the library and review all calls to circular_storage::clear().

**Comment by tap** [comment]
Good catch!

**Comment by nwolek** [comment]
Did the sweep today. The use in delay.h is the only one that makes sense to change.
