### ISSUE TITLE
flesh out interpolation in delay object

### ISSUE THREAD

**Issue by nwolek** [Cycling74/min-lib#34]
Both head() and tail() operators need a variation that can interpolate between samples. The [tail()](https://github.com/Cycling74/min-lib/blob/master/include/c74_lib_circular_storage.h#L166) is a higher priority because of its current use in allpass().

**Comment by nwolek** [comment]
Now I remember that we planned to design delay object with interpolation, but leave circular_storage more basic and general. Therefore changing the name on this issue.

Looking at the code, there is already some [limited interpolation in delay here](https://github.com/Cycling74/min-lib/blob/master/include/c74_lib_delay.h#L80).

**Comment by nwolek** [comment]
My attempts to swap between interpolators are not working. Here is [one resource I was reading](https://stackoverflow.com/questions/25973103/copy-swap-in-base-and-derived-class), but struggling to find the right syntax. Might be because I need a more specific operator definition.

**Comment by nwolek** [comment]
Question for @tap - any opinion on what the default interpolation type should be for delay?

**Comment by tap** [comment]
In Max for `tapin~` and `tapout~` it is cubic.
