### ISSUE TITLE
generators for ramp and triangle do not generate the correct number of cycles

### ISSUE THREAD

**Issue by tap** [Cycling74/min-lib#4]
unless that number of cycles is 1

sine and cosine both work properly.

need unit tests for this in all cases.

**Comment by nwolek** [comment]
During Skype chat w Tim this morning, we agreed that it would be good to have the following unit tests for each generator:
- 1/4 cycle (less than one)
- 3 cycles (more than one)
- 2.5 cycles (more than one, but not integral)
