### ISSUE TITLE
Where should milliseconds to samples function be defined?

### ISSUE THREAD

**Issue by nwolek** [Cycling74/min-lib#40]
It seems this formula will get used several places in the library:

`new_size_ms * 0.001 * sampling_frequency`

In order to remain DRY, we should define it once in a location that is accessible to all our code. Perhaps as a non-member function in `c74_lib.h`? Or should it be a pre-processor macro?

Any thoughts @tap?

**Comment by nwolek** [comment]
@tap - Sorry I overlooked `c74_lib_math.h` as another obvious option. You designed these functions, so I would be curious to hear your criteria for what to include v exclude here.

**Comment by tap** [comment]
I would definitely prefer a small inline function to a macro.

Either location seems defensible to me.
